version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    links:
      - api
    restart: always
    volumes:
      - ./org-chimata-ssl-certs:/var/lib/https-portal
    environment:
      CLIENT_MAX_BODY_SIZE: 1024M
      # DOMAINS: 'api.game-boomin.net -> http://api:1129, admin.game-boomin.net -> http://admin:8001'
      DOMAINS: 'api.localhost -> http://api:1129, admin.localhost -> http://admin:8001'
      # STAGE: 'production'
      STAGE: 'local'
    # extra_hosts:
    #   - "localhost:192.168.1.188"

  api:
    build: ./api
    tty: true
    ports:
      - 1129:1129
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db

  admin:
    build: ./nginx/admin
    ports:
      - 8001:8001
    volumes:
      - ./html/admin:/var/www/html
      - ./log/admin:/var/log/nginx
      - ./nginx/admin/sites:/etc/nginx/conf.d

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: game
      MYSQL_ROOT_PASSWORD: game
      MYSQL_USER: game
      MYSQL_PASSWORD: game
      TZ: "Asia/Tokyo"
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  # node:
  #   build: ./admin
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./admin:/usr/src/app
  #   tty: true
  #   extra_hosts:
  #     - "localhost:192.168.0.13"
  #   depends_on:
  #     - api